const STORAGE={questions:'nrtc_questions_v1',submissions:'nrtc_submissions_v1',registrations:'nrtc_registrations_v1',attempts:'nrtc_attempts_v1'};
const USER_HASH='33ffe8a22f3334029c255b5dfbe185aece1601e97ce5826144595d6f25b0895b';
const PASS_HASH='7b83dbc566b12c00fbc5003d71fe15cffe38172578ef27aac0f03709abb7854c';
const $=id=>document.getElementById(id), load=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}, save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let editIndex=-1;
function ensure(){if(!localStorage.getItem(STORAGE.questions))save(STORAGE.questions,window.DEFAULT_QUESTIONS)}
async function sha(s){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
$('loginBtn').onclick=async()=>{const ok=(await sha($('adminUser').value))===USER_HASH&&(await sha($('adminPass').value))===PASS_HASH;if(!ok){$('loginMsg').textContent='ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง';$('loginMsg').classList.remove('hidden');return}sessionStorage.setItem('nrtc_admin','1');openAdmin()};
function openAdmin(){$('loginCard').classList.add('hidden');$('adminApp').classList.remove('hidden');renderAll()}
$('logoutBtn').onclick=()=>{sessionStorage.removeItem('nrtc_admin');location.reload()};
function scoreOf(s){let correct=0;(s.answers||[]).forEach((a,i)=>{if(a===s.questionSnapshot?.[i]?.correct)correct++});return {correct,score:+(correct*20/50).toFixed(2)}}
function fmtDate(x){try{return new Date(x).toLocaleString('th-TH')}catch{return x||'-'}}
function renderAll(){const qs=load(STORAGE.questions,[]),regs=load(STORAGE.registrations,[]),subs=load(STORAGE.submissions,[]);$('mQuestions').textContent=qs.length;$('mRegs').textContent=regs.length;$('mSubs').textContent=subs.length;const vals=subs.map(scoreOf);$('mAvg').textContent=vals.length?(vals.reduce((a,b)=>a+b.score,0)/vals.length).toFixed(2):'0.00';renderResults(subs);renderRegs(regs);renderQuestions(qs)}
function renderResults(subs){const tb=$('resultRows');tb.innerHTML='';subs.slice().reverse().forEach((s,revIndex)=>{const realIndex=subs.length-1-revIndex,sc=scoreOf(s),tr=document.createElement('tr');tr.innerHTML=`<td>${fmtDate(s.submittedAt)}</td><td>${esc(s.student?.studentId)}</td><td>${esc(s.student?.name)}</td><td>${esc(s.student?.className)}</td><td>${esc(s.student?.department)}</td><td>${esc(s.status)}</td><td>${sc.correct}/50</td><td><b>${sc.score.toFixed(2)}</b></td><td><button class="btn danger small" data-i="${realIndex}">ลบ</button></td>`;tr.querySelector('button').onclick=()=>{if(confirm('ลบผลสอบรายการนี้?')){const a=load(STORAGE.submissions,[]);a.splice(realIndex,1);save(STORAGE.submissions,a);renderAll()}};tb.appendChild(tr)})}
function renderRegs(regs){const tb=$('regRows');tb.innerHTML='';regs.slice().reverse().forEach((r,revIndex)=>{const realIndex=regs.length-1-revIndex,tr=document.createElement('tr');tr.innerHTML=`<td>${fmtDate(r.registeredAt)}</td><td>${esc(r.studentId)}</td><td>${esc(r.name)}</td><td>${esc(r.className)}</td><td>${esc(r.department)}</td><td><button class="btn danger small">ลบ/รีเซ็ต</button></td>`;tr.querySelector('button').onclick=()=>{if(confirm('ลบข้อมูลผู้ลงทะเบียนและรีเซ็ตสิทธิ์เข้าสอบของเลขนักศึกษานี้?')){const a=load(STORAGE.registrations,[]);const id=a[realIndex]?.studentId;a.splice(realIndex,1);save(STORAGE.registrations,a);const at=load(STORAGE.attempts,{});delete at[id];save(STORAGE.attempts,at);renderAll()}};tb.appendChild(tr)})}
function renderQuestions(qs){const list=$('questionList');list.innerHTML='';qs.forEach((q,i)=>{const d=document.createElement('div');d.className='admin-question';d.innerHTML=`<div class="qtitle">ข้อ ${i+1}. ${esc(q.q)}</div><ol type="A">${q.options.map((o,j)=>`<li class="${j===Number(q.correct)?'correct':''}">${esc(o)}</li>`).join('')}</ol><div class="row"><button class="btn secondary small edit">แก้ไข</button><button class="btn danger small del">ลบ</button></div>`;d.querySelector('.edit').onclick=()=>editQ(i);d.querySelector('.del').onclick=()=>{if(confirm('ลบข้อสอบข้อนี้?')){const a=load(STORAGE.questions,[]);a.splice(i,1);save(STORAGE.questions,a);renderAll()}};list.appendChild(d)})}
function editQ(i){const q=load(STORAGE.questions,[])[i];editIndex=i;$('qText').value=q.q;$('qLevel').value=q.level||'basic';$('qCorrect').value=String(q.correct);q.options.forEach((o,j)=>$(`o${j}`).value=o);$('qExplain').value=q.explain||'';$('saveQuestion').textContent='บันทึกการแก้ไข';$('cancelEdit').classList.remove('hidden');scrollTo({top:$('tab-questions').offsetTop-20,behavior:'smooth'})}
function clearQForm(){editIndex=-1;['qText','o0','o1','o2','o3','qExplain'].forEach(id=>$(id).value='');$('qLevel').value='basic';$('qCorrect').value='0';$('saveQuestion').textContent='เพิ่มข้อสอบ';$('cancelEdit').classList.add('hidden');$('qMsg').classList.add('hidden')}
$('saveQuestion').onclick=()=>{const q={level:$('qLevel').value,q:$('qText').value.trim(),options:[0,1,2,3].map(i=>$(`o${i}`).value.trim()),correct:Number($('qCorrect').value),explain:$('qExplain').value.trim()};if(!q.q||q.options.some(x=>!x)){$('qMsg').textContent='กรุณากรอกคำถามและตัวเลือกทั้ง 4 ข้อให้ครบ';$('qMsg').classList.remove('hidden');return}const a=load(STORAGE.questions,[]);if(editIndex>=0)a[editIndex]=q;else a.push(q);save(STORAGE.questions,a);clearQForm();renderAll()};$('cancelEdit').onclick=clearQForm;
$('resetQuestions').onclick=()=>{if(confirm('คืนค่าคลังข้อสอบเป็นชุดเริ่มต้น 50 ข้อ? ข้อที่แก้ไขหรือเพิ่มจะถูกแทนที่')){save(STORAGE.questions,window.DEFAULT_QUESTIONS);clearQForm();renderAll()}};
$('clearResults').onclick=()=>{if(confirm('ลบผลสอบทั้งหมด?')){save(STORAGE.submissions,[]);renderAll()}};$('clearRegs').onclick=()=>{if(confirm('ลบข้อมูลลงทะเบียนและรีเซ็ตสิทธิ์เข้าสอบทั้งหมด?')){save(STORAGE.registrations,[]);save(STORAGE.attempts,{});renderAll()}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');['results','registrations','questions','backup'].forEach(t=>$(`tab-${t}`).classList.toggle('hidden',t!==b.dataset.tab))});
$('exportBtn').onclick=()=>{const data={exportedAt:new Date().toISOString(),questions:load(STORAGE.questions,[]),registrations:load(STORAGE.registrations,[]),submissions:load(STORAGE.submissions,[]),attempts:load(STORAGE.attempts,{})};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nrtc-exam-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(d.questions)save(STORAGE.questions,d.questions);if(d.registrations)save(STORAGE.registrations,d.registrations);if(d.submissions)save(STORAGE.submissions,d.submissions);if(d.attempts)save(STORAGE.attempts,d.attempts);renderAll();alert('นำเข้าข้อมูลสำเร็จ')}catch{alert('ไฟล์ JSON ไม่ถูกต้อง')}};
function esc(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML}
ensure();if(sessionStorage.getItem('nrtc_admin')==='1')openAdmin();
