import { auth, db, isFirebaseConfigured } from './firebase-service.js';
import { ADMIN_USERNAME, ADMIN_AUTH_EMAIL, ADMIN_UID } from './firebase-config.js';
import { signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import { collection, getDocs, doc, setDoc, deleteDoc, writeBatch, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';

const $=id=>document.getElementById(id);let questionRows=[],answerMap=new Map(),editId=null;
function esc(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML}
function fmtDate(x){if(!x)return '-';try{const d=x.toDate?x.toDate():new Date(x);return d.toLocaleString('th-TH')}catch{return '-'}}
$('loginBtn').onclick=async()=>{
  $('loginMsg').classList.add('hidden');
  if(!isFirebaseConfigured()){ $('loginMsg').textContent='ยังไม่ได้ตั้งค่า Firebase ใน firebase-config.js';$('loginMsg').classList.remove('hidden');return; }
  if($('adminUser').value.trim()!==ADMIN_USERNAME){$('loginMsg').textContent='ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง';$('loginMsg').classList.remove('hidden');return}
  $('loginBtn').disabled=true;
  try{await signInWithEmailAndPassword(auth,ADMIN_AUTH_EMAIL,$('adminPass').value)}catch(e){console.error(e);$('loginMsg').textContent='ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง หรือยังไม่ได้สร้างบัญชี Admin ใน Firebase Authentication';$('loginMsg').classList.remove('hidden')}
  $('loginBtn').disabled=false;
};
$('logoutBtn').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{if(user && ADMIN_UID && !ADMIN_UID.startsWith('PASTE_') && user.uid===ADMIN_UID){$('loginCard').classList.add('hidden');$('adminApp').classList.remove('hidden');renderAll()}else{if(user) await signOut(auth);$('loginCard').classList.remove('hidden');$('adminApp').classList.add('hidden')}});
async function fetchAll(){
  const [q,a,r,s]=await Promise.all([getDocs(collection(db,'questions')),getDocs(collection(db,'answerKeys')),getDocs(collection(db,'registrations')),getDocs(collection(db,'submissions'))]);
  questionRows=q.docs.map(d=>({id:d.id,...d.data()}));answerMap=new Map(a.docs.map(d=>[d.id,d.data()]));
  return {questions:questionRows,registrations:r.docs.map(d=>({id:d.id,...d.data()})),submissions:s.docs.map(d=>({id:d.id,...d.data()}))};
}
function scoreOf(s){let correct=0;(s.questionIds||[]).forEach((qid,i)=>{const key=answerMap.get(qid);if(key && Number(s.selectedOriginal?.[i])===Number(key.correct))correct++});return {correct,score:+(correct*20/50).toFixed(2)}}
async function renderAll(){
  try{
    const {questions,registrations,submissions}=await fetchAll();$('mQuestions').textContent=questions.length;$('mRegs').textContent=registrations.length;$('mSubs').textContent=submissions.length;const vals=submissions.map(scoreOf);$('mAvg').textContent=vals.length?(vals.reduce((x,y)=>x+y.score,0)/vals.length).toFixed(2):'0.00';renderResults(submissions);renderRegs(registrations);renderQuestions(questions);
  }catch(e){console.error(e);alert('อ่านข้อมูลจาก Firebase ไม่สำเร็จ กรุณาตรวจสอบ Firestore Rules และการตั้งค่า Firebase')}
}
function renderResults(subs){const tb=$('resultRows');tb.innerHTML='';subs.sort((a,b)=>(b.submittedAt?.seconds||0)-(a.submittedAt?.seconds||0)).forEach(s=>{const sc=scoreOf(s),tr=document.createElement('tr');tr.innerHTML=`<td>${fmtDate(s.submittedAt||s.submittedAtClient)}</td><td>${esc(s.student?.studentId)}</td><td>${esc(s.student?.name)}</td><td>${esc(s.student?.className)}</td><td>${esc(s.student?.department)}</td><td>${esc(s.status)}</td><td>${sc.correct}/50</td><td><b>${sc.score.toFixed(2)}</b></td><td><button class="btn danger small">ลบ</button></td>`;tr.querySelector('button').onclick=async()=>{if(confirm('ลบผลสอบรายการนี้?')){await deleteDoc(doc(db,'submissions',s.id));renderAll()}};tb.appendChild(tr)})}
function renderRegs(regs){const tb=$('regRows');tb.innerHTML='';regs.sort((a,b)=>(b.registeredAt?.seconds||0)-(a.registeredAt?.seconds||0)).forEach(r=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${fmtDate(r.registeredAt||r.registeredAtClient)}</td><td>${esc(r.studentId)}</td><td>${esc(r.name)}</td><td>${esc(r.className)}</td><td>${esc(r.department)}</td><td><button class="btn danger small">ลบ/รีเซ็ต</button></td>`;tr.querySelector('button').onclick=async()=>{if(confirm('ลบข้อมูลลงทะเบียนเพื่ออนุญาตให้เลขนักศึกษานี้เข้าสอบใหม่?')){await deleteDoc(doc(db,'registrations',r.id));renderAll()}};tb.appendChild(tr)})}
function renderQuestions(qs){const list=$('questionList');list.innerHTML='';qs.sort((a,b)=>(a.order||0)-(b.order||0)).forEach((q,i)=>{const key=answerMap.get(q.id)||{},d=document.createElement('div');d.className='admin-question';d.innerHTML=`<div class="qtitle">ข้อ ${i+1}. ${esc(q.q)}</div><ol type="A">${(q.options||[]).map((o,j)=>`<li class="${j===Number(key.correct)?'correct':''}">${esc(o)}</li>`).join('')}</ol><div class="row"><button class="btn secondary small edit">แก้ไข</button><button class="btn danger small del">ลบ</button></div>`;d.querySelector('.edit').onclick=()=>editQ(q.id);d.querySelector('.del').onclick=async()=>{if(confirm('ลบข้อสอบข้อนี้?')){const b=writeBatch(db);b.delete(doc(db,'questions',q.id));b.delete(doc(db,'answerKeys',q.id));await b.commit();renderAll()}};list.appendChild(d)})}
function editQ(id){const q=questionRows.find(x=>x.id===id),key=answerMap.get(id)||{};editId=id;$('qText').value=q.q;$('qLevel').value=q.level||'basic';$('qCorrect').value=String(key.correct??0);q.options.forEach((o,j)=>$(`o${j}`).value=o);$('qExplain').value=key.explain||'';$('saveQuestion').textContent='บันทึกการแก้ไข';$('cancelEdit').classList.remove('hidden');scrollTo({top:$('tab-questions').offsetTop-20,behavior:'smooth'})}
function clearQForm(){editId=null;['qText','o0','o1','o2','o3','qExplain'].forEach(id=>$(id).value='');$('qLevel').value='basic';$('qCorrect').value='0';$('saveQuestion').textContent='เพิ่มข้อสอบ';$('cancelEdit').classList.add('hidden');$('qMsg').classList.add('hidden')}
$('saveQuestion').onclick=async()=>{const q={level:$('qLevel').value,q:$('qText').value.trim(),options:[0,1,2,3].map(i=>$(`o${i}`).value.trim()),active:true,updatedAt:serverTimestamp()},key={correct:Number($('qCorrect').value),explain:$('qExplain').value.trim(),updatedAt:serverTimestamp()};if(!q.q||q.options.some(x=>!x)){$('qMsg').textContent='กรุณากรอกคำถามและตัวเลือกทั้ง 4 ข้อให้ครบ';$('qMsg').classList.remove('hidden');return}const id=editId||crypto.randomUUID();const b=writeBatch(db);b.set(doc(db,'questions',id),q,{merge:true});b.set(doc(db,'answerKeys',id),key,{merge:true});await b.commit();clearQForm();renderAll()};$('cancelEdit').onclick=clearQForm;
$('resetQuestions').textContent='นำเข้าชุดข้อสอบ JSON';
$('resetQuestions').onclick=()=>document.getElementById('seedFile').click();
const seedInput=document.createElement('input');seedInput.type='file';seedInput.accept='application/json';seedInput.id='seedFile';seedInput.hidden=true;document.body.appendChild(seedInput);
seedInput.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const arr=JSON.parse(await f.text());if(!Array.isArray(arr)||arr.length<50)throw new Error('ไฟล์ต้องเป็น array และมีอย่างน้อย 50 ข้อ');if(!confirm(`นำเข้าข้อสอบ ${arr.length} ข้อ และแทนที่คลังข้อสอบปัจจุบันทั้งหมด?`))return;const oldQ=await getDocs(collection(db,'questions')),oldA=await getDocs(collection(db,'answerKeys'));let b=writeBatch(db),n=0;for(const d of [...oldQ.docs,...oldA.docs]){b.delete(d.ref);if(++n>=400){await b.commit();b=writeBatch(db);n=0}}for(let i=0;i<arr.length;i++){const x=arr[i],id=x.id||`q-${String(i+1).padStart(3,'0')}`;b.set(doc(db,'questions',id),{q:x.q,options:x.options,level:x.level||'basic',active:true,order:i+1});b.set(doc(db,'answerKeys',id),{correct:Number(x.correct),explain:x.explain||''});n+=2;if(n>=400){await b.commit();b=writeBatch(db);n=0}}if(n)await b.commit();alert('นำเข้าคลังข้อสอบสำเร็จ');clearQForm();renderAll()}catch(err){console.error(err);alert('นำเข้าไม่สำเร็จ: '+err.message)}finally{e.target.value=''}};
$('clearResults').onclick=async()=>{if(!confirm('ลบผลสอบทั้งหมด?'))return;const s=await getDocs(collection(db,'submissions'));await deleteDocs(s.docs);renderAll()};$('clearRegs').onclick=async()=>{if(!confirm('ลบข้อมูลลงทะเบียนทั้งหมดและเปิดสิทธิ์เข้าสอบใหม่ทั้งหมด?'))return;const s=await getDocs(collection(db,'registrations'));await deleteDocs(s.docs);renderAll()};
async function deleteDocs(docs){for(let i=0;i<docs.length;i+=400){const b=writeBatch(db);docs.slice(i,i+400).forEach(d=>b.delete(d.ref));await b.commit()}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');['results','registrations','questions','backup'].forEach(t=>$(`tab-${t}`).classList.toggle('hidden',t!==b.dataset.tab))});
$('exportBtn').onclick=async()=>{const {questions,registrations,submissions}=await fetchAll();const keys=[...answerMap.entries()].map(([id,v])=>({id,...v}));const data={exportedAt:new Date().toISOString(),questions,answerKeys:keys,registrations,submissions};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nangrong-exam-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('importFile').onchange=async()=>alert('สำหรับเวอร์ชัน Firebase ให้ใช้ปุ่ม “นำเข้าชุดข้อสอบ JSON” ในแท็บจัดการข้อสอบ ส่วนการคืนข้อมูลผลสอบควรทำจาก Firebase Console เพื่อป้องกันการเขียนข้อมูลผิดชุด');
